Milestone5
eypsrcnuygr/my-calculator pull request #6
Opened 2020-12-11 07:43 UTC by eypsrcnuygr

- You should follow your operation on the screen. 
- If you press AC one time it'll clean the next and operation and turn operation to AC. After that, if you want to go with the next number, you should change your operation to whatever you would like to use.
- After adding '.' signs into your numbers you need to change the operation again to make your operation works.
- '%' sign is taking the second number as the numerator and after you click the '=' sign the result will come to the total's place.
- If you click operations in the beginning, the app will be frozen.

2020-12-11 10:06 UTC, uche-inyama requested changes
## Changes Required

### Hi @eypsrcnuygr :wave: 

Your project looks good, however, it needs some refactoring.

- [ ] First,  your **app component**. In the [project scope](https://microverse.pathwright.com/library/react-redux-v11/184438/path/step/106376019/), it is required that you create only a handleClick function, that accepts buttonName as an argument, your function does not accept button name as an argument.

- [ ] It is required you pass handleClick as a prop to buttonPanel not handleChange.
[screen shot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone5/app/passHandleClick.png).

Kindly follow the [structure](https://microverse.pathwright.com/library/react-redux-v11/184438/path/step/106376019/) provided in the project requirements. This would make your code base neat and easy to follow.

- [ ]  After clearing the display component, when **AC** is left, if I perform an operation I get this error.

![errrr](https://user-images.githubusercontent.com/46329537/101889046-3fbb2400-3b9f-11eb-8159-11b51fecb91f.png)

### That is it, implement these changes, then submit another form for a code review.

### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

2020-12-11 21:56 UTC, shloch approved these changes
Hello @eypsrcnuygr 

Great job with the progress. I noticed you improved from the previous review.
Now we're almost done, I will disturb you further with a minor detail as we're rounding up.
Could you please handle an edge case scenario here ?. It's about 'DIVISION BY ZERO' error.
Handle that by displaying something like "`infinity`" or "`NAN`" (something like that)

[see screenshot below]

![calc](https://user-images.githubusercontent.com/40712459/101958681-197b9f80-3c04-11eb-9a03-3d0d594729fe.gif)

2020-12-11 21:56 UTC, shloch commented on src/Components/App.js
>    }
great job

2020-12-11 21:56 UTC, shloch commented on src/Components/ButtonPanel.js
>            />
good

2020-12-11 21:59 UTC, shloch commented
Sorry i approved on github above by error by error, this is not approved on the dashboard, waiting for a final review with the bug mentioned above though before you get a final thumbs up

Happy coding

2020-12-12 01:02 UTC, christianotieno approved these changes
### Milestone Approved 🍾 
Hello @eypsrcnuygr  👋 
 ##
This milestone has met all the required changes needed for approval. 👏 
Congratulations on the hard work done on this milestone. Good job 👍 
I will go ahead and mark this as complete. Good luck with the next tasks 🥇 
##
### Happy coding 💻 
#### Christian Otieno (TSE)

2020-12-12 08:55 UTC, merged